"""Allow NULL in service_id and cascade delete behavior

Revision ID: 261a43008347
Revises: 8890c487f1de
Create Date: 2024-11-26 13:38:07.097637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261a43008347'
down_revision = '8890c487f1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
